// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjTMrXE20DXz_dOk2AeAEDtySEpXPHYPc',
    appId: '1:273960341234:web:a66ef258358d563fb1ca6b',
    messagingSenderId: '273960341234',
    projectId: 'pickl-cd6e3',
    authDomain: 'pickl-cd6e3.firebaseapp.com',
    storageBucket: 'pickl-cd6e3.firebasestorage.app',
    measurementId: 'G-KX5XJGLCP6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnfF2hDgMsUGDRhZ2zGtp9w76seTBfIzs',
    appId: '1:273960341234:android:9dc4172f4a36e3a5b1ca6b',
    messagingSenderId: '273960341234',
    projectId: 'pickl-cd6e3',
    storageBucket: 'pickl-cd6e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyblQ-kEhJbxPwtal62tE-1WZpXRrUwZg',
    appId: '1:273960341234:ios:8b59830840319c05b1ca6b',
    messagingSenderId: '273960341234',
    projectId: 'pickl-cd6e3',
    storageBucket: 'pickl-cd6e3.firebasestorage.app',
    iosBundleId: 'com.example.picklnairted',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyblQ-kEhJbxPwtal62tE-1WZpXRrUwZg',
    appId: '1:273960341234:ios:8b59830840319c05b1ca6b',
    messagingSenderId: '273960341234',
    projectId: 'pickl-cd6e3',
    storageBucket: 'pickl-cd6e3.firebasestorage.app',
    iosBundleId: 'com.example.picklnairted',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjTMrXE20DXz_dOk2AeAEDtySEpXPHYPc',
    appId: '1:273960341234:web:3fdca1d962eb967eb1ca6b',
    messagingSenderId: '273960341234',
    projectId: 'pickl-cd6e3',
    authDomain: 'pickl-cd6e3.firebaseapp.com',
    storageBucket: 'pickl-cd6e3.firebasestorage.app',
    measurementId: 'G-EX20N36925',
  );
}
